# Generated by Django 5.2.3 on 2025-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/images/')),
                ('category', models.ManyToManyField(related_name='books', to='category.category')),
            ],
        ),
    ]
