# Generated by Django 5.2.1 on 2025-06-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_borrow_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
