# Generated by Django 5.2.1 on 2025-06-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrow_balance_after_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='balance_after_transaction',
        ),
        migrations.AddField(
            model_name='borrow',
            name='balance_after_borrow',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='balance_after_return',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
