# Generated by Django 5.2.1 on 2025-06-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_borrow_balance_after_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='balance_after_borrow',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='review',
            name='ratting',
            field=models.CharField(choices=[('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('3', '⭐⭐⭐'), ('2', '⭐⭐'), ('1', '⭐')], default='1', max_length=20),
        ),
    ]
