# Generated by Django 5.2.1 on 2025-06-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comt',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_at',
        ),
    ]
