# Generated by Django 5.1.6 on 2025-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
