# Generated by Django 5.1.6 on 2025-04-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
