# Generated by Django 5.2.1 on 2025-06-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='balance_after_transection',
            new_name='balance_after_transaction',
        ),
    ]
