# Generated by Django 5.1.6 on 2025-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument_type',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('drums', 'Drums'), ('flute', 'Flute')], default='other', max_length=200),
        ),
    ]
