# Generated by Django 5.1.6 on 2025-04-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_instrument_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument_type',
            field=models.CharField(choices=[('duff', 'Duff'), ('flute', 'Flute'), ('piano', 'Piano'), ('drums', 'Drums'), ('guitar', 'Guitar'), ('other', 'Other')], default='other', max_length=200),
        ),
    ]
