# Generated by Django 5.1.6 on 2025-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_assign_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(related_name='tasks', to='category_app.category')),
            ],
        ),
    ]
