# Generated by Django 5.1.6 on 2025-04-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(related_name='tasks', to='task_app.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_assign_date',
            field=models.DateTimeField(),
        ),
    ]
